WFSServices/config/routes.rb
Rails.application.routes.draw do
  
  get 'home', to: 'home#index', as: :home
  get 'home/search', to: 'home#search', as: :search

  resources :service_contacts
  resources :service_locations
  resources :costs
  resources :services
  resources :service_types
  resources :locations
  resources :categories
  resources :locations
  resources :contacts
  resources :comments

  devise_for :users
  scope "/admin" do
    resources :users
  end

  root to:'services#index'
end

WFSServices/app/models/service_location.rb
class ServiceLocation < ApplicationRecord
  belongs_to :service
  belongs_to :location

  validates_presence_of :service
  validates_presence_of :location


  validate :service_location_is_not_a_duplicate, on: :create


private 
  def service_location_is_not_a_duplicate
    if service_location_exists? 
      errors.add(:service_location_id, "this assignment already exists.")
    end
  end

  def service_location_exists?
    !ServiceLocation.where(service_id: self.service_id, location_id: self.location_id).empty?
  end

end

WFSServices/app/controllers/service_locations_controller.rb
class ServiceLocationsController < ApplicationController
  before_action :set_service_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  authorize_resource

  # GET /service_locations
  # GET /service_locations.json
  def index
    @service_locations = ServiceLocation.all
  end

  # GET /service_locations/1
  # GET /service_locations/1.json
  def show
  end

  # GET /service_locations/new
  def new
    @service_location = ServiceLocation.new
    unless params[:service_id].nil?
      @service = Service.find(params[:service_id])
    end
  end

  # GET /service_locations/1/edit
  def edit
  end

  # POST /service_locations
  # POST /service_locations.json
  def create
    @service_location = ServiceLocation.new(service_location_params)
    if @service_location.save
      flash[:notice] = "Successfully added '#{@service_location.location.name}' as a contact for '#{@service_location.service.name}'."
      redirect_to service_path(@service_location.service)
    else
      @service = Service.find(params[:service_location][:service_id])
        render action: 'new', locals: { service: @service }
    end
  end

  # PATCH/PUT /service_locations/1
  # PATCH/PUT /service_locations/1.json
  def update
    respond_to do |format|
      if @service_location.update(service_location_params)
        format.html { redirect_to @service_location, notice: "Updated Information for location: '#{@service_location.location.name}'" }
        format.json { render :show, status: :ok, location: @service_location }
      else
        format.html { render :edit }
        format.json { render json: @service_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_locations/1
  # DELETE /service_locations/1.json
  def destroy
    @service_location = ServiceLocation.find(params[:id])
    if @service_location.destroy
      flash[:notice] = "Successfully removed '#{@service_location.location.name}' as a location for '#{@service_location.service.name}'."
      redirect_to @service_location.service
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_location
      @service_location = ServiceLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_location_params
      params.require(:service_location).permit(:service_id, :location_id, :created_at, :updated_at)
    end
end

WFSServices/app/helpers/service_locations_helper.rb
module ServiceLocationsHelper
end

WFSServices/app/views/service_locations/_form.html.erb
<div class="container">
    <div class="card">
        <div class="card-content is-light-grey">
                <%= simple_form_for(@service_location) do |f| %>
                    <%= f.error_notification %>

                        <div class="field">
                            <div class="control">

                                <% exist_locations = Array[] %>
                                <% @service.locations.each do |sc| %>
                                    <% exist_locations << sc %>
                                <% end %>

                                <%= f.input :location_id, collection: (Location.alphabetical.to_a - exist_locations), include_blank: true, wrapper: false %>
                            </div>
                        </div>

                        <%= f.input :service_id, as: :hidden, input_html: { value: @service.id }, wrapper:false %>

                        <%= f.input :created_at, as: :hidden, input_html: { value: Date.current }, wrapper:false %>

                    <%= f.button :submit, "Add Location" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

WFSServices/app/views/service_locations/_form_new.html.erb
<div class="container">
    <div class="card">
        <div class="card-content is-light-grey">
                <%= simple_form_for(@service_location) do |f| %>
                    <%= f.error_notification %>

                        <div class="field">
                            <div class="control">

                                <% exist_locations = Array[] %>
                                <% @service.locations.each do |sc| %>
                                    <% exist_locations << sc %>
                                <% end %>

                                <%= f.input :location_id, collection: (Location.alphabetical.to_a - exist_locations), include_blank: true, wrapper: false %>
                            </div>
                        </div>

                        <%= f.input :service_id, as: :hidden, input_html: { value: @service.id }, wrapper:false %>
                        <%= f.input :created_by, as: :hidden, input_html: { value: current_user.username }, wrapper:false %>
                        <%= f.input :created_at, as: :hidden, input_html: { value: Date.current }, wrapper:false %>

                    <%= f.button :submit, "Add Location" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

WFSServices/app/views/service_locations/edit.html.erb
<h1>Editing Service Location</h1>

<%= render 'form_edit', service_location: @service_location %>

<%= link_to 'Show', @service_location %> |
<%= link_to 'Back', service_locations_path %>

WFSServices/app/views/service_locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Service Locations</h1>

<table>
  <thead>
    <tr>
      <th>Service</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_locations.each do |service_location| %>
      <tr>
        <td><%= service_location.service %></td>
        <td><%= service_location.location %></td>
        <td><%= link_to 'Show', service_location %></td>
        <td><%= link_to 'Edit', edit_service_location_path(service_location) %></td>
        <td><%= link_to 'Destroy', service_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service Location', new_service_location_path %>

WFSServices/app/views/service_locations/new.html.erb
<div class="container">
  <div class="row columns">
    <div class="column">
      <br/>
      <p class="title is-4 no-padding">Add Location to Service</p>
    </div>
  </div>
</div>

<%= render 'form_new', service_location: @service_location %>

<div class="container">
  <div class="row columns">
    <div class="column">
    <br>
      <%= link_to 'Back', @service, class: "button is-info is-rounded" %>
    </div>
  </div>
</div>

WFSServices/app/views/service_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service:</strong>
  <%= @service_location.service %>
</p>

<p>
  <strong>Location:</strong>
  <%= @service_location.location %>
</p>

<%= link_to 'Edit', edit_service_location_path(@service_location) %> |
<%= link_to 'Back', service_locations_path %>