WFSServices/config/routes.rb
Rails.application.routes.draw do
  
  get 'home', to: 'home#index', as: :home
  get 'home/search', to: 'home#search', as: :search

  resources :service_contacts
  resources :service_locations
  resources :costs
  resources :services
  resources :service_types
  resources :locations
  resources :categories
  resources :locations
  resources :contacts
  resources :comments

  devise_for :users
  scope "/admin" do
    resources :users
  end

  root to:'services#index'
end

WFSServices/app/models/service_contact.rb
class ServiceContact < ApplicationRecord
  belongs_to :service
  belongs_to :contact

  validates_presence_of :service
  validates_presence_of :contact

  validate :service_contact_is_not_a_duplicate, on: :create


private 
  def service_contact_is_not_a_duplicate
    if service_contact_exists? 
      errors.add(:service_contact_id, "this assignment already exists.")
    end
  end

  def service_contact_exists?
    !ServiceContact.where(service_id: self.service_id, contact_id: self.contact_id).empty?
  end
end

WFSServices/app/controllers/service_contacts_controller.rb
class ServiceContactsController < ApplicationController
  before_action :set_service_contact, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  authorize_resource


  # GET /service_contacts
  # GET /service_contacts.json
  def index
    @service_contacts = ServiceContact.all
  end

  # GET /service_contacts/new
  def new
    @service_contacts = ServiceContact.all
    @service_contact = ServiceContact.new
    unless params[:service_id].nil?
      @service = Service.find(params[:service_id])
      @current_contacts = @service.service_contacts.map{ |c| c.id }
    end
  end

  # GET /service_contacts/1/edit
  def edit
  end

  # POST /service_contacts
  # POST /service_contacts.json
  def create
    @service_contact = ServiceContact.new(service_contact_params)
    if @service_contact.save
      flash[:notice] = "Successfully added '#{@service_contact.contact.name}' as a contact for '#{@service_contact.service.name}'."
      redirect_to service_path(@service_contact.service)
    else
      @service = Service.find(params[:service_contact][:service_id])
      render action: 'new', locals: { service: @service }
    end
  end

  # DELETE /service_contacts/1
  # DELETE /service_contacts/1.json
  def destroy
    @service_contact = ServiceContact.find(params[:id])
    if @service_contact.destroy
      flash[:notice] = "Successfully removed '#{@service_contact.contact.name}' as a contact for '#{@service_contact.service.name}'."
      redirect_to @service_contact.service
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_contact
      @service_contact = ServiceContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_contact_params
      params.require(:service_contact).permit(:service_id, :contact_id, :created_at, :updated_at)
    end
end

WFSServices/app/helpers/service_contacts_helper.rb
module ServiceContactsHelper
end

WFSServices/app/views/service_contacts/_form.html.erb
<div class="container">
    <div class="card">
        <div class="card-content is-light-grey">
                <%= simple_form_for(@service_contact) do |f| %>
                    <%= f.error_notification %>

                        <div class="field">
                            <div class="control">

                                <% exist_contacts = Array[] %>
                                <% @service.contacts.each do |sc| %>
                                    <% exist_contacts << sc %>
                                <% end %>

                                <%= f.input :contact_id, collection: (Contact.alphabetical.to_a - exist_contacts), include_blank: true, wrapper: false %>
                            </div>
                        </div>
                        
                        <%= f.input :service_id, as: :hidden, input_html: { value: @service.id }, wrapper:false %>
                        <%= f.input :created_by, as: :hidden, input_html: { value: current_user.username }, wrapper:false %>
                        <%= f.input :created_at, as: :hidden, input_html: { value: Date.current }, wrapper:false %>

                    <%= f.button :submit, "Add Contact" %>

                <% end %>
            </div>
        </div>
    </div>
</div>

WFSServices/app/views/service_contacts/edit.html.erb
<h1>Editing Service Contact</h1>

<%= render 'form', service_contact: @service_contact %>

<%= link_to 'Show', @service_contact %> |
<%= link_to 'Back', service_contacts_path %>

WFSServices/app/views/service_contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Service Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Service</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_contacts.each do |service_contact| %>
      <tr>
        <td><%= service_contact.service %></td>
        <td><%= service_contact.contact %></td>
        <td><%= link_to 'Show', service_contact %></td>
        <td><%= link_to 'Edit', edit_service_contact_path(service_contact) %></td>
        <td><%= link_to 'Destroy', service_contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service Contact', new_service_contact_path %>

WFSServices/app/views/service_contacts/new.html.erb
<div class="container">
  <div class="row columns">
    <div class="column">
      <br/>
      <p class="title is-4 no-padding">Add Contact to Service</p>
    </div>
  </div>
</div>

<%= render 'form', service_contact: @service_contact %>

<div class="container">
  <div class="row columns">
    <div class="column">
    <br>
      <%= link_to 'Back', @service, class: "button is-info is-rounded" %>
    </div>
  </div>
</div>

WFSServices/app/views/service_contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service:</strong>
  <%= @service_contact.service %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @service_contact.contact %>
</p>

<%= link_to 'Edit', edit_service_contact_path(@service_contact) %> |
<%= link_to 'Back', service_contacts_path %>