WFSServices/config/routes.rb
Rails.application.routes.draw do
  
  get 'home', to: 'home#index', as: :home
  get 'home/search', to: 'home#search', as: :search

  resources :service_contacts
  resources :service_locations
  resources :costs
  resources :services
  resources :service_types
  resources :locations
  resources :categories
  resources :locations
  resources :contacts
  resources :comments

  devise_for :users
  scope "/admin" do
    resources :users
  end

  root to:'services#index'
end

WFSServices/app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
    <!-- <a href="#" class="close">&times;</a> -->
    <%= msg %>
  </div>
<% end %>

WFSServices/app/views/partials/_nav.html.erb
<nav class="navbar is-purple">
    <div class="container">
        <div class="navbar-brand">

            <span class="navbar-burger burger" data-target="navbarMenu">
                <span></span>
                <span></span>
                <span></span>
            </span>
        </div>  

        <div id="navbarMenu" class="navbar-menu">
            <div class="navbar-start">
                <% if can? :read, Service %>
                    <span class="navbar-item">
                        <%= link_to "Services", services_path, style: 'color:#FFFFFF; font-size: 20px;', class: 'css_class' %>
                    </span>
                <% end %>

                <% if can? :read, Location %>
                    <span class="navbar-item">
                        <%= link_to "Locations", locations_path, style: 'color:#FFFFFF; font-size: 20px;', class: 'css_class' %>
                    </span>
                <% end %>

                <% if can? :read, Contact %>
                    <span class="navbar-item">
                        <%= link_to "Contacts", contacts_path, style: 'color:#FFFFFF; font-size: 20px;', class: 'css_class' %>
                    </span>
                <% end %>

                <% if logged_in? && current_user.admin? %>
                    <span class="navbar-item">
                        <%= link_to "Users", users_path, style: 'color:#FFFFFF; font-size: 20px;', class: 'css_class' %>
                    </span>
                <% end %>
            </div>

            <div class="navbar-end">
                <span class="navbar-item">
                    <%= render :partial => "partials/search" %>
                </span>
            </div>

    </div>
</nav>

WFSServices/app/views/partials/_search.html.erb
<%# <div class="box">
    <div class="field has-addons">
        <div class="control">
            <input class="input" type="search" placeholder="Search...">
        </div>
        <div class="control">
            <a class="button is-info">Search</a>
        </div>
    </div>
</div> %>

<%# <div class="field is-grouped">
  <p class="control is-expanded"> %>

<div class="padding-left">  
  <%= form_tag(search_path, method: :get, class: "form-inline", id: "search") do %>
      <%= text_field_tag 'query'%>
      <%= submit_tag "Search", class: 'button is-info is-small' %>
  <% end %>
</div>

WFSServices/app/views/partials/_topbar.html.erb
<div class="row valign-wrapper topbar">

  <div class="col s4 padding-left padding-right padding-top">

  	<div class="columns is-multiline is-mobile">

    	<div class="column is-8"><%= image_tag('white_logo.png', height: '50%', width: '50%') %></div>

    	<div class="column is-4">
		   	<div class="signin_item padding-left">

			    <% if user_signed_in? %>

			        <p>Signed in as <%= current_user.username %></p>
			        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

			    <% else %>
			        <%= link_to "Sign in", new_user_session_path %></p>
			    <% end %>

		    </div>
    	</div>
    </div>

  </div>

</div>
</div>